language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - travis_retry composer update --prefer-source --no-interaction

script:
  - vendor/bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
